FROM openjdk:11-jre-slim

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip3 install pyspark==3.4.1 psycopg2-binary

WORKDIR /app

COPY weather_app/setup_consumer_spark.py .
COPY weather_app/constants.py .


CMD ["python3", "setup_consumer_spark.py"]