FROM python:3.12-slim

WORKDIR /app

COPY weather_app/main.py .
COPY weather_app/constants.py .

RUN pip install fastapi sqlalchemy psycopg2-binary uvicorn

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]