FROM openjdk:11-jre-slim

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip3 install pyspark==3.4.1 psycopg2-binary

WORKDIR /app

COPY weather_app/consumer.py .
COPY weather_app/constants.py .


CMD ["python3", "consumer.py"]