services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 #PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgresql:
    image: postgres:15
    environment:
      POSTGRES_USER: weather_app_user
      POSTGRES_PASSWORD: weather_app_pass
      POSTGRES_DB: weather_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  create-table:
    build:
      context: .
      dockerfile: Dockerfile-table
    depends_on:
      - postgresql

  setup-producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    depends_on:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1

  setup-consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - postgresql
      - setup-producer

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8000:8000"
    depends_on:
      - create-table

volumes:
  pgdata:

